# Generated by Django 3.1.5 on 2021-01-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_payment_payment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
