# Generated by Django 3.1.5 on 2021-01-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_auto_20210113_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Payment Failed', max_length=100),
        ),
    ]
