# Generated by Django 3.1.5 on 2021-01-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='customer',
        ),
        migrations.AddField(
            model_name='ebook',
            name='product_file',
            field=models.FileField(default='settings.MEDIA_ROOT/ebooks/ebook.epub', upload_to='ebooks/'),
        ),
    ]
