# Generated by Django 3.1.5 on 2021-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('SKU', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Image_URL', models.URLField(unique=True)),
            ],
        ),
    ]
