# Generated by Django 3.1.5 on 2021-01-19 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_avgproductratings_productreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 13, 29, 52, 559295, tzinfo=utc)),
        ),
    ]
