# Generated by Django 3.1.5 on 2021-01-19 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_productreviews_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
