# Generated by Django 3.1.5 on 2021-01-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210119_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avgproductratings',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='avgproductratings',
            name='id',
        ),
        migrations.AddField(
            model_name='avgproductratings',
            name='no_of_ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='avgproductratings',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Products.product'),
        ),
    ]
