# Generated by Django 3.1.5 on 2021-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210119_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='comment',
            field=models.TextField(),
        ),
    ]
