# Generated by Django 3.1.5 on 2021-01-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210119_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avgproductratings',
            name='no_of_ratings',
            field=models.IntegerField(),
        ),
    ]
