# Generated by Django 3.1.5 on 2021-01-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20210119_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Products.product')),
                ('copies_sold', models.IntegerField()),
            ],
        ),
    ]
